version: '3.8'
services:
  app:
    container_name: go-mux-clean
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - psql
    networks:
      - go-api

  psql:
    image: postgres:latest
    container_name: psql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - go-api

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - psql
    ports:
      - 5051:80
    networks:
      - go-api
    restart: unless-stopped

volumes:
  api:
  psql:


networks:
  go-api:
    driver: bridge
